
use residence;
INSERT INTO `residence`.`anteproyectos` (`id`, `ANT_nombre`, `ANT_descripcion`, `EST_id`) VALUES
 ('1', 'educacion en el hogar y la escuela es el metodo mas infalible', 'octener con estadisticas y entrevistas a los alumnos como es que sus padres les enseñan la educacion', '1', NULL),
 ('2', '', 'descripcion', '1'),
('3', 'enseñanza en el trabajo en equipo y en grupo', 'colaborar a los adolecentes a un mejor comportamiento al trabajo en equipo para realizar sus trabajos', '1'),
('4', ' dirigir a un estudiante aun mayor comportamiento ala hora de participar ', 'tener mayor comportamiento en clases ala hora de participar', '1'),
('5', 'enseñanza de los valores que debe entender un ser humano', 'participacion de los padres para inculcar valores alos adolecentes', '1'),
('6', 'involucrar al alumnado para apoyar a los padres de familia con los labores de la casa ', 'involucrar alos padres de familia para una mayor comunicacion ala hora de los labores de la casa', '1'),
('7', 'enseñanza para que el alumnado tenga mayor comunicacion con sus padres generando apoyo y bienestar', 'tener charlas con el alumnado y los padres de familia', '1'),
('8', 'enseñanza al servicio laboral para un aprendizaje a futuro', 'tener practicas como un profesional con informacion especifica', '1'),
('9', 'recreacion del alumno implementando todos sus conocimientos adquiridos durante su instancia en la escuela', 'apoyar en la enseñanza del alumno y evaluarlo y recrear el conocimiente de cada semestre', '1'),
('10', 'estrategia didactica y administrativa para una mejor enseñanza basica en el alumno', 'usar estrategias para una mejor enseñanza', '1'),
('11', 'motivacion extra para enseñarle alo alumnos regularisarse con sus trabajos', 'regularizacion con sus trabajos', '1'),
('12', 'comprension y y entendimiento de todos y cada uno de los alumnos', 'tener seguridad en que el alumnado entiende y habla del tema', '1'),
('13', 'propuesta de lectura al alumnado de todas las formas de leccion', 'aprender las leccionese entendidas', '1'),
('14', 'disposicion de informacion aportuda para agregar', 'descripcion', '1'),
('15', 'correcion de lectura todos pueden aprender', ' los alumnos pueden aprender de diferentes maneras de la mejor forma', '1'),
('16', 'comprension de lectura ', 'el alumno interpreta la lectura de una forma correcta ', '1'),
('17', 'escritura de forma correcta', 'el alumno escribe de una forma correcta', '1'),
('18', 'aprendizaje en la redaccion del alumno', 'redactar de una forma correcta', '1'),
('19', 'aprendizaje de exposicion de manera intuitiva', 'aprender a un mayor manejo de palabra', '1'),
('20', 'concientizar a un mejor colaboracion y comunicacion con los docentes de las escuelas', 'comunicacion con los docentes', '1'),
('21', 'aprendizaje de busqueda de proyectos', 'hacer mejores investigaciones', '1'),
('22', 'interpretacion y colaboracion para aprender de forma autonoma', 'aprendizaje autonomo', '1'),
('23', 'recreacion de aprendizaje adquirido en total de materias', 'aprendizaje de todas las materias en un sierto tiempo', '1'),
('24', 'aprendizaje de contener materias y relacionarlas para un servicio laboral', 'relacion dematerias para un servicio laboral', '1'),
('25', 'localizar y detectar un mal aprendizaje por parte de un alumno', 'detectar el mal aprendizaje', '1'),
('26', 'aprender con el alumno y generar un mayor aprendizaje', 'el aprendizaje debe ser mutuo', '1');