APP_ENV=local
APP_DEBUG=true
APP_KEY=base64:eHolNU47M+fIGw3pOL5rEM1No20Lhi4VCzHi6nsvA0M=
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=5.79.67.193
DB_PORT=3306
DB_DATABASE=enufchilpancingo
DB_USERNAME=enufdb
DB_PASSWORD=2016Grants

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null